

spring:
    datasource:
        password: 11
        url: "jdbc:postgresql://localhost:5432/crowd"
        username: root
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                format_sql: true